
<ul>
<li><a href="#demo+handling">Demo Handling</a></li>
<li><a href="#match+tools">Match Tools</a></li>
</ul>

<h2 id="demo+handling">Demo Handling</h2>

<h3 id="cl_demopinginterval">cl_demoPingInterval</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"5"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="cl_demospeed">cl_demospeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">
Controls the speed of demo playback in percentage (can be changed during demo playback if you wish).

</p><p class="remarks">
</p>
<h3 id="demo_capture_dir">demo_capture_dir</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"capture"</span></p><p class="description">

Change the default capture directory.

</p><p class="remarks"></p>
<h3 id="demo_capture_fps">demo_capture_fps</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"30.0"</span></p><p class="description">

Change the default capture fps.

</p><p class="remarks"></p>
<h3 id="demo_capture_steadycam">demo_capture_steadycam</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

Changes behaviour of keyboard/mouse input when capturing.

</p><p class="remarks"></p>
<h3 id="demo_dir">demo_dir</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>""</span></p><p class="description">

Change the demos and autorecord directory.

</p><p class="remarks"></p>
<h3 id="demo_getpings">demo_getpings</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="qizmo_dir">qizmo_dir</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"qizmo"</span></p><p class="description">

Change the default qizmo directory.

</p><p class="remarks"></p>
<h2 id="match+tools">Match Tools</h2>

<h3 id="match_auto_logconsole">match_auto_logconsole</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_auto_minlength">match_auto_minlength</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"30"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_auto_record">match_auto_record</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_auto_spectating">match_auto_spectating</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_auto_sshot">match_auto_sshot</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_2on2">match_format_2on2</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"2on2/%n - [%k%v%l] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_3on3">match_format_3on3</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"tdm/%n - [%Oon%E_%t%v%e] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_4on4">match_format_4on4</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"tdm/%n - [%Oon%E_%t%v%e] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_arena">match_format_arena</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"arena/%n - %p%v%e - [%F_frags] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_coop">match_format_coop</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"coop/%n - [%C_player_coop] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_duel">match_format_duel</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"duel/%n - %p%v%e - [dmm%D] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_ffa">match_format_ffa</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"ffa/%n - [%C_player_ffa] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_race">match_format_race</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"race/%n - [race] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_solo">match_format_solo</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"solo/%n - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_tdm">match_format_tdm</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"tdm/%n - [%Oon%E_%t%v%e] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_tf_clanwar">match_format_tf_clanwar</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"tfwar/%n - [%Oon%E_%t%v%e] - [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_format_tf_duel">match_format_tf_duel</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"tfduel/%n - %p%v%e [%M]"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_name_and">match_name_and</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"_&amp;_"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_name_nick">match_name_nick</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>""</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_name_on">match_name_on</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"on"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_name_spec">match_name_spec</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"(SPEC)"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="match_name_versus">match_name_versus</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"_vs_"</span></p><p class="description"></p><p class="remarks"></p>