
<ul>
<li><a href="#input+-+joystick">Input - Joystick</a></li>
<li><a href="#input+-+keyboard">Input - Keyboard</a></li>
<li><a href="#input+-+misc">Input - Misc</a></li>
<li><a href="#input+-+mouse">Input - Mouse</a></li>
</ul>

<h2 id="input+-+joystick">Input - Joystick</h2>

<h3 id="joystick">joystick</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga unsupported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h2 id="input+-+keyboard">Input - Keyboard</h2>

<h3 id="allow_scripts">allow_scripts</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"2"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="cl_anglespeedkey">cl_anglespeedkey</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1.5"</span></p><p class="description">
This variable sets multiplier by which your &quot;cl_yawspeed&quot; (how fast you turn) is
multiplied when running (+speed).

</p><p class="remarks">
</p>
<h3 id="cl_backspeed">cl_backspeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"200"</span></p><p class="description">

This allows you to set your backward speed. Obviously this is also limited by
the server, usually to &quot;320&quot;.

</p><p class="remarks"></p>
<h3 id="cl_forwardspeed">cl_forwardspeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"200"</span></p><p class="description">

This allows you to set your forward speed. Obviously this is also limited by the
server, usually to &quot;320&quot;.

</p><p class="remarks"></p>
<h3 id="cl_keypad">cl_keypad</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>QW compatibility where the keypad keys act the same key name, eg KP_8 acts like uparrow would.</td></tr><tr><td>1</td><td>You will be able to bind such keys as capslock, numlock, and all numpad keys.</td></tr></tbody></table><p class="remarks">


</p>
<h3 id="cl_movespeedkey">cl_movespeedkey</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"2.0"</span></p><p class="description">
This variable is the multiplier for how fast you move when running (+speed) in
relation to when walking (-speed).

</p><p class="remarks">
</p>
<h3 id="cl_pitchspeed">cl_pitchspeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"150"</span></p><p class="description">

This variable determines how fast you you turn up/down when using &quot;+lookup&quot; and
&quot;+lookdown&quot;.

</p><p class="remarks"></p>
<h3 id="cl_showkeycodes">cl_showkeycodes</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga unsupported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="cl_sidespeed">cl_sidespeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"350"</span></p><p class="description">

This allows you to set your strafe speed. Obviously this is also limited by the
server, usually to &quot;320&quot;.

</p><p class="remarks"></p>
<h3 id="cl_smartjump">cl_smartjump</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Off.</td></tr><tr><td>1</td><td>Will convert +jump commands to +moveup commands when underwater.</td></tr></tbody></table><p class="remarks">


</p>
<h3 id="cl_upspeed">cl_upspeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"200"</span></p><p class="description">
This allows you to set the speed with which you move up and down in liquids or in spectator mode.
Obviously this is also limited by the server, usually to 320*0.7 = 224 when underwater and to 500 in spectator mode.

</p><p class="remarks">
</p>
<h3 id="cl_yawspeed">cl_yawspeed</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"140"</span></p><p class="description">

This variable defines how quickly you turn left (+left) or right (+right).

</p><p class="remarks"></p>
<h2 id="input+-+misc">Input - Misc</h2>

<h3 id="freelook">freelook</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Both -mlook and freelook 0 must be specified to disable free look mode.</td></tr><tr><td>1</td><td>Enables free look mode, that is, moving the mouse forward and back moves your view </td></tr></tbody></table><p class="remarks">

direction up or down.

</p>
<h3 id="lookspring">lookspring</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">
This variable toggles the centering of the screen after the -klook command.
</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Disable automatic force_centerview.</td></tr><tr><td>1</td><td>Enable automatic force_centerview.</td></tr></tbody></table><p class="remarks">



</p>
<h3 id="lookstrafe">lookstrafe</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">
This variable toggles the automatic strafing when the +klook command is used.
When set to &quot;1&quot; and the player used the +klook command, the keys that are bound 
to the +left and +right commands will now act as if they were bound to +moveleft 
and +moveright. This command was put it in order to allow keyboard player to 
combine the +strafe and +klook commands into one.
This command also has effect on the mouse controls. When set to &quot;1&quot; moving the 
mouse left and right will make the player move left and right instead of making 
him turn left and right.

</p><p class="range">Range: 0/1</p><p class="remarks">
</p>
<h3 id="sensitivity">sensitivity</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"3"</span></p><p class="description">

This variable sets the sensitivity of the mouse, it is one of the most important 
variables in the whole game.

</p><p class="remarks"></p>
<h2 id="input+-+mouse">Input - Mouse</h2>

<h3 id="m_accel">m_accel</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

Sets mouse acceleration like in q3.

</p><p class="range">Range: 0..1</p><p class="remarks"></p>
<h3 id="m_filter">m_filter</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

This variable toggles mouse input filtering. When set to &quot;1&quot;, the values which
are received from the mouse's input will first be averaged together and then 
that value will be used in the game. 
The reason for this command is that some mice had problems with sending sporadic
coordinates which make the input from the mouse jerky, also when using a serial 
or PS/2 mouse, the Windows operating system will only sample mouse input every 
25ms, that is 40 times a second (for USB mice the sample rate is 125 Hz, that is
every 8 ms). When set to &quot;1&quot; this variable will smooth out the input but it will 
cause latency between the movement of the mouse and the actual response in the 
game. When using a PS/2 mouse it is thus first recommended to try to increase 
the sampling rate either by changing it via your mouse driver or by using the 
ps2rate program which can be downloaded at ps2rate homepage . 
If you are playing the game at frame rates above 40 FPS and if you can't 
increase the sampling rate of your PS/2 rate or if you are playing with a serial 
mouse it is recommended that you enable this toggle.

</p><p class="range">Range: 0/1</p><p class="remarks"></p>
<h3 id="m_forcewheel">m_forcewheel</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga unsupported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Disable.</td></tr><tr><td>1</td><td>If you have problems to get MWHEELUP and MWHEELDOWN working set this to 1.</td></tr></tbody></table><p class="remarks">


</p>
<h3 id="m_forward">m_forward</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">
This variable controls how fast the player should move forward and back when the 
mouse is moved forward and back. This command has no effect if the +mlook 
command is in effect because when the mouse is moved forward and back the 
player looks up and down instead of moving forward and back. Some players might 
want to set this variable to &quot;0&quot; if they happen not to use +mlook constantly and 
they only want to use the mouse to turn the player. Setting this variable to &quot;0&quot;
will prevent the inadvertent movement of the player forward and back while 
trying to make precise turns with the mouse.

</p><p class="remarks">
</p>
<h3 id="m_pitch">m_pitch</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0.022"</span></p><p class="description">

This variable sets the level of precision when the mouse is used to make the 
player look up and down while the +mlook command is in effect. By default this 
variable is set in such a way that moving the mouse forward makes the player 
look up and moving the mouse backward makes the player look down. Some people 
prefer to have this movement inverted just like it is inverted for airplane 
controls. If you wish to use this inverted mouse movement then you should set 
this variable to a negative value (for example &quot;-0.022&quot;). It is a matter of 
preference which movement method is used by players. Also lowering the value 
for this variable will increase the level of precision when the mouse is used 
to make the player look up and down. This variable can be used separately from 
the sensitivity variable to provide greater control over the mouse sensitivity 
for movement along the pitch. It is advisable to keep the value for this 
variable constant at 0.022 or -0.022 and instead use the sensitivity variable 
to change the overall sensitivity of the mouse. Also, some script writers lower 
the value for this variable along with a lowered value for the fov variable in 
order to provide more precision when the fov variable is used to zoom.

</p><p class="remarks"></p>
<h3 id="m_side">m_side</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0.8"</span></p><p class="description">
When the +strafe command is active or when &quot;lookspring&quot; is set to &quot;1&quot; this 
variable is used to control the sensitivity when the mouse is moved left and 
right to make the player move left and right.

</p><p class="remarks">
</p>
<h3 id="m_yaw">m_yaw</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0.022"</span></p><p class="description">

This variable controls how fast the player turns left and right when the mouse 
is moved left and right. It is recommended that this variable be left alone and
instead the &quot;sensitivity&quot; variable is used to change the level of precision. 
If you set this variable to a negative value you will reverse the mouse 
movement. Some script writers use this variable to increase the level of 
precision when the &quot;fov&quot; variable is used to zoom the screen.

</p><p class="remarks"></p>
<h3 id="mouse1">mouse1</h3>
<p class="support"><span class="windows-software unsupported">Windows: Software</span> <span class="windows-opengl unsupported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"+attack"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mouse2">mouse2</h3>
<p class="support"><span class="windows-software unsupported">Windows: Software</span> <span class="windows-opengl unsupported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"+strafe"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mouse3">mouse3</h3>
<p class="support"><span class="windows-software unsupported">Windows: Software</span> <span class="windows-opengl unsupported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"+forward"</span></p><p class="description"></p><p class="remarks"></p>