  <ul>
    <li><a href="#server-settings">Server Settings</a></li>
    <li><a href="#serverside-permissions">Serverside Permissions</a></li>
    <li><a href="#serverside-physics">Serverside Physics</a></li>
  </ul>
<h2 id="server-settings">Server Settings</h2>
  <h3 id="coop">coop&nbsp;<span>[<a href="#coop">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable cooperative.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable cooperative.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="filterban">filterban&nbsp;<span>[<a href="#filterban">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Only IP addresses on the Ban list will be allowed onto the server.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Only IP addresses NOT on the Ban list will be allowed onto the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="floodprotmsg">floodprotmsg&nbsp;<span>[<a href="#floodprotmsg">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span></span></p>
<div>
  <h4>Description</h4>
  <p>
Sets the message displayed after flood protection is invoked.
Example: floodprotmsg "Shut up whiner!"

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="pausable">pausable&nbsp;<span>[<a href="#pausable">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable pause.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable pause.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="skill">skill&nbsp;<span>[<a href="#skill">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>easy level for singleplaying.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Normal level for singleplaying.</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Hard level for singleplaying.</td>
      </tr>
      <tr>
        <td>3</td>
        <td>Nightmare level for singleplaying.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>






</p>
</div>

  <h3 id="sv_aim">sv_aim&nbsp;<span>[<a href="#sv_aim">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>2</span></p>
<div>
  <h4>Description</h4>
  <p>
Sets the value for auto-aiming leniency.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="sv_cheats">sv_cheats&nbsp;<span>[<a href="#sv_cheats">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable cheats.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable cheats. (need map realoading)</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="sv_fastconnect">sv_fastconnect&nbsp;<span>[<a href="#sv_fastconnect">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
actually no help.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="sv_highchars">sv_highchars&nbsp;<span>[<a href="#sv_highchars">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable high character color names for players.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="sv_loadentfiles">sv_loadentfiles&nbsp;<span>[<a href="#sv_loadentfiles">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable custom map entity file support.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="sv_mapcheck">sv_mapcheck&nbsp;<span>[<a href="#sv_mapcheck">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable map checksumming to check for players who edit maps to cheat.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>


Note: A player who has edited his map files to cheat by removing textures 
from walls will not be able to join the server and play.


</p>
</div>

  <h3 id="sv_maxpitch">sv_maxpitch&nbsp;<span>[<a href="#sv_maxpitch">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>80</span></p>
<div>
  <h4>Description</h4>
  <p>server-side variable for setting maximum of view angles
</p>
  <h4>Value</h4>
    <p>Integer. By default, in quakeworld maximum viewangle is '80'. You can set for example '90' then you will be able look directly to sky. q3 players should like it</p>
  <h4>Remarks</h4>
  <p>EZQuake and ZQuake (may be some other) clients understand this physics change, old clients will be clamped at [-70~80] (quakeworld default) view angles.</p>
</div>

  <h3 id="sv_maxrate">sv_maxrate&nbsp;<span>[<a href="#sv_maxrate">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
Maximum rate for clients.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="sv_maxtic">sv_maxtic&nbsp;<span>[<a href="#sv_maxtic">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0.1</span></p>
<div>
  <h4>Description</h4>
  <p>

The maximum amount of time in seconds before a client a receives an update 
from the server.

</p>
</div>

  <h3 id="sv_minpitch">sv_minpitch&nbsp;<span>[<a href="#sv_minpitch">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>-70</span></p>
<div>
  <h4>Description</h4>
  <p>server-side variable for setting minimum of view angles</p>
  <h4>Value</h4>
    <p>Integer. By default, in quakeworld minimum viewangle is '-70'. You can set for example '-90' then you will be able look directly to floor. q3 players should like it.</p>
  <h4>Remarks</h4>
  <p>EZQuake and ZQuake (may be some other) clients understand this physics change, old clients will be clamped at [-70~80] (quakeworld default) view angles.</p>
</div>

  <h3 id="sv_mintic">sv_mintic&nbsp;<span>[<a href="#sv_mintic">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>

The minimum amount of time the server will wait before sending packets to 
a client.

</p>
</div>

  <h3 id="sv_nailhack">sv_nailhack&nbsp;<span>[<a href="#sv_nailhack">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Allows nails in most cases to uses less bandwidth and to fly around </td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>

smoother and point in the right direction.


</p>
</div>

  <h3 id="sv_phs">sv_phs&nbsp;<span>[<a href="#sv_phs">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Has something to do with the table which is build at the loading time</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>


of the map.


</p>
</div>

  <h3 id="sv_spectalk">sv_spectalk&nbsp;<span>[<a href="#sv_spectalk">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Players can't hear spectators.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Players can hear spectators.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="timeout">timeout&nbsp;<span>[<a href="#timeout">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>65</span></p>
<div>
  <h4>Description</h4>
  <p>
Sets the amount of time in seconds before a client is considered disconnected 
if the server does not receive a packet.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="zombietime">zombietime&nbsp;<span>[<a href="#zombietime">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>2</span></p>
<div>
  <h4>Description</h4>
  <p>

The number of minutes that the server will keep the character of a player on 
the map who seems to have disconnected.

</p>
</div>

<h2 id="serverside-permissions">Serverside Permissions</h2>
  <h3 id="allow_download">allow_download&nbsp;<span>[<a href="#allow_download">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Clients can download game data from the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="allow_download_maps">allow_download_maps&nbsp;<span>[<a href="#allow_download_maps">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Clients can download .bsp map files from the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="allow_download_models">allow_download_models&nbsp;<span>[<a href="#allow_download_models">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Clients can download .mdl files from the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="allow_download_pakmaps">allow_download_pakmaps&nbsp;<span>[<a href="#allow_download_pakmaps">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Clients can download map files in paks from the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="allow_download_skins">allow_download_skins&nbsp;<span>[<a href="#allow_download_skins">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Clients can download .pcx skin files from the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="allow_download_sounds">allow_download_sounds&nbsp;<span>[<a href="#allow_download_sounds">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Clients can download .wav sound files from the server.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

<h2 id="serverside-physics">Serverside Physics</h2>
  <h3 id="pm_airstep">pm_airstep&nbsp;<span>[<a href="#pm_airstep">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>

  <h3 id="pm_bunnyspeedcap">pm_bunnyspeedcap&nbsp;<span>[<a href="#pm_bunnyspeedcap">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span></span></p>
<div>
  <h4>Description</h4>
  <p>
This is experimental code intended to restore class balance in TF. If you set 
this cvar to something like 1.5 or 2, a solider will not be able to bunnyhop as 
fast as a scout does :) Note that this cvar is optional and disabled by default, 
so it will in NO WAY affect gameplay unless you set it explicitly to anything 
but 0.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="pm_ktjump">pm_ktjump&nbsp;<span>[<a href="#pm_ktjump">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1 or 0.5 or 0.5 or 0.5</span></p>
<div>
  <h4>Description</h4>
  <p>

You can change value of ktjump.

</p>
</div>

  <h3 id="pm_pground">pm_pground&nbsp;<span>[<a href="#pm_pground">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>Enables 'persistent onground flag' physics tweak.  Makes pm_airstep work better;  otherwise it's pretty useless.</p>
  <h4>Value</h4>
    <p>Integer. </p>
  <h4>Remarks</h4>
  <p>This extension makes use of Z_EXT_PF_ONGROUND to ensure correct movement prediction by clients.

Prediction errors shouldn't be very noticeable anyway even with old clients.

You're not expected to understand this.</p>
</div>

  <h3 id="pm_slidefix">pm_slidefix&nbsp;<span>[<a href="#pm_slidefix">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span></span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Upon decsension from a sloped surface, the player doesn't</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>

"drop" (which is a bug in QW), but smoothly slides, as it was in NQ.


</p>
</div>

  <h3 id="sv_accelerate">sv_accelerate&nbsp;<span>[<a href="#sv_accelerate">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>10</span></p>
<div>
  <h4>Description</h4>
  <p>
Sets the acceleration value for the player.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="sv_airaccelerate">sv_airaccelerate&nbsp;<span>[<a href="#sv_airaccelerate">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>10</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets how quickly the player accelerates in air.

</p>
</div>

  <h3 id="sv_friction">sv_friction&nbsp;<span>[<a href="#sv_friction">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>4</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the friction value for the player.

</p>
</div>

  <h3 id="sv_gravity">sv_gravity&nbsp;<span>[<a href="#sv_gravity">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>800</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the global value for the amount of gravity.

</p>
</div>

  <h3 id="sv_maxspeed">sv_maxspeed&nbsp;<span>[<a href="#sv_maxspeed">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>320</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the maximum speed a player can move.

</p>
</div>

  <h3 id="sv_maxvelocity">sv_maxvelocity&nbsp;<span>[<a href="#sv_maxvelocity">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>2000</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the maximum velocity an object can travel.

</p>
</div>

  <h3 id="sv_spectatormaxspeed">sv_spectatormaxspeed&nbsp;<span>[<a href="#sv_spectatormaxspeed">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>500</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the maximum speed a spectator can move.

</p>
</div>

  <h3 id="sv_stopspeed">sv_stopspeed&nbsp;<span>[<a href="#sv_stopspeed">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>100</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the value that determines how fast the player should come to a complete stop.

</p>
</div>

  <h3 id="sv_wateraccelerate">sv_wateraccelerate&nbsp;<span>[<a href="#sv_wateraccelerate">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>10</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the water acceleration value.

</p>
</div>

  <h3 id="sv_waterfriction">sv_waterfriction&nbsp;<span>[<a href="#sv_waterfriction">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>4</span></p>
<div>
  <h4>Description</h4>
  <p>

Sets the water friction value.

</p>
</div>

