
<ul>
<li><a href="#mp3+settings">MP3 Settings</a></li>
<li><a href="#sound+settings">Sound Settings</a></li>
</ul>

<h2 id="mp3+settings">MP3 Settings</h2>

<h3 id="mp3_grabvolume">mp3_grabvolume</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"2"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mp3_scrolltitle">mp3_scrolltitle</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mp3_showtime">mp3_showtime</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mp3_volume">mp3_volume</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mp3_winamp_dir">mp3_winamp_dir</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx unsupported">Linux: GLX</span> <span class="linux-svga unsupported">Linux: SVGA</span> </p><p class="default">Default: <span>"c:/program files/winamp"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mp3_xmms_dir">mp3_xmms_dir</h3>
<p class="support"><span class="windows-software unsupported">Windows: Software</span> <span class="windows-opengl unsupported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"/usr/local/bin"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="mp3_xmms_session">mp3_xmms_session</h3>
<p class="support"><span class="windows-software unsupported">Windows: Software</span> <span class="windows-opengl unsupported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h2 id="sound+settings">Sound Settings</h2>

<h3 id="bgmvolume">bgmvolume</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">
This variable sets the volume of the CD music.

</p><p class="remarks">
</p>
<h3 id="cl_staticsounds">cl_staticSounds</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Disable static sounds.</td></tr><tr><td>1</td><td>Enable static sounds.</td></tr></tbody></table><p class="remarks">


</p>
<h3 id="s_ambientfade">s_ambientfade</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"100"</span></p><p class="description">
How fast the volume of ambient sounds changes as you move around the map.

</p><p class="remarks">
</p>
<h3 id="s_ambientlevel">s_ambientlevel</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0.3"</span></p><p class="description">

Volume level of ambient sounds (produced by water and sky brushes).

</p><p class="remarks"></p>
<h3 id="s_initsound">s_initsound</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">


</p><p class="remarks"></p>
<h3 id="s_khz">s_khz</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"11"</span></p><p class="description">

Sound quality. Must be set from the commandline
Example:
fuhquake +set s_khz 44

</p><p class="range">Range: 11/22/44</p><p class="remarks"></p>
<h3 id="s_loadas8bit">s_loadas8bit</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Off.</td></tr><tr><td>1</td><td>On (The sound samples will be loaded in 8-bit mode thus making them a little smaller. </td></tr></tbody></table><p class="remarks">

This will give a little performance boost when playing the game at the cost of 
quality for the sound samples.)

</p>
<h3 id="s_mixahead">s_mixahead</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0.1"</span></p><p class="description">
This variable defines the delay time for sounds. How low you can set your sound
mixahead depends on your FPS, when you set it too low, your sound will start 
crackling. Generally, with 72 FPS you should be able to use a delay of 0.06 
seconds, if you use the command-line switch &quot;-primarysound&quot;, you may be able to
go even lower, but results may vary on this.

</p><p class="remarks">
</p>
<h3 id="s_noextraupdate">s_noextraupdate</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">

</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Makes Quake update its sound buffers more often to avoid choppy sound when your fps is really low (20 or worse)</td></tr><tr><td>1</td><td>Don't use extra sound updates.  Gives a slight fps boost, but may lead to choppy sound on low-end machines</td></tr></tbody></table><p class="remarks">


</p>
<h3 id="s_nosound">s_nosound</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">
</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Enable the playback of sounds.</td></tr><tr><td>1</td><td>Disable the playback of sounds.  Note that it effectively just resets sound volume to zero, but the sound engine still runs.  If you want disable sound in order to get more fps, use the -nosound command line option instead.</td></tr></tbody></table><p class="remarks">



</p>
<h3 id="s_precache">s_precache</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"1"</span></p><p class="description">
</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Disable automatic sound caching.</td></tr><tr><td>1</td><td>Enable automatic sound caching.</td></tr></tbody></table><p class="remarks">



</p>
<h3 id="s_show">s_show</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description">
</p><p class="range">Range: 0/1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>Disable that the number of currently playing sound files is displayed.</td></tr><tr><td>1</td><td>Enable that the number of currently playing sound files is displayed.</td></tr></tbody></table><p class="remarks">



</p>
<h3 id="s_swapstereo">s_swapstereo</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0"</span></p><p class="description"></p><p class="remarks"></p>
<h3 id="volume">volume</h3>
<p class="support"><span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p><p class="default">Default: <span>"0.7"</span></p><p class="description">
</p><p class="range">Range: 0..1</p><table class="values"><thead><tr><td>Val</td><td>Description</td></tr></thead><tbody><tr><td>
0</td><td>No sound.</td></tr><tr><td>1</td><td>Maximum volume.</td></tr></tbody></table><p class="remarks">



</p>