  <ul>
    <li><a href="#mp3-settings">MP3 Settings</a></li>
    <li><a href="#sound-settings">Sound Settings</a></li>
  </ul>
<h2 id="mp3-settings">MP3 Settings</h2>
  <h3 id="mp3_grabvolume">mp3_grabvolume&nbsp;<span>[<a href="#mp3_grabvolume">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>2</span></p>
<div>
  <h4>Description</h4>
  <p>Toggles client control of your music player volume.</p>
  <h4>Value</h4>
    <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0 = False</td>
        <td>Do not get / set volume of your music player.</td>
      </tr>
      <tr>
        <td>1 = True</td>
        <td>Control volume of your music player.</td>
      </tr>
    </tbody>
  </table>
  </div>

  <h3 id="mp3_scrolltitle">mp3_scrolltitle&nbsp;<span>[<a href="#mp3_scrolltitle">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>Toggles scrolling of the song info in mp3 player control window.</p>
  <h4>Value</h4>
    <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0 = False</td>
        <td>Do not scroll song info text.</td>
      </tr>
      <tr>
        <td>1 = True</td>
        <td>Enable song info scrolling.</td>
      </tr>
    </tbody>
  </table>
  </div>

  <h3 id="mp3_showtime">mp3_showtime&nbsp;<span>[<a href="#mp3_showtime">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>Toggles displaying song time information in mp3 player control window.</p>
  <h4>Value</h4>
    <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0</td>
        <td>Do not display song time information.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Display song time and total time of currently played song.</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Display remaining time only.</td>
      </tr>
    </tbody>
  </table>
  </div>

  <h3 id="mp3_volume">mp3_volume&nbsp;<span>[<a href="#mp3_volume">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1 or 0.37 or 0.37</span></p>
<div>
  <h4>Description</h4>
  <p>Controls volume of your external music player.</p>
  <h4>Value</h4>
    <p>Float. Use values from 0 to 1.</p>
  </div>

  <h3 id="mp3_winamp_dir">mp3_winamp_dir&nbsp;<span>[<a href="#mp3_winamp_dir">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 unsupported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>c:/program files/winamp</span></p>
<div>
  <h4>Description</h4>
  <p>Tells your client the path where it should look for your external music player.</p>
  <h4>Value</h4>
    <p>String. </p>
  </div>

<h2 id="sound-settings">Sound Settings</h2>
  <h3 id="bgmvolume">bgmvolume&nbsp;<span>[<a href="#bgmvolume">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
This variable sets the volume of the CD music.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="cl_staticsounds">cl_staticSounds&nbsp;<span>[<a href="#cl_staticsounds">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable static sounds.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable static sounds.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="s_ambientfade">s_ambientfade&nbsp;<span>[<a href="#s_ambientfade">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>100</span></p>
<div>
  <h4>Description</h4>
  <p>
How fast the volume of ambient sounds changes as you move around the map.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="s_ambientlevel">s_ambientlevel&nbsp;<span>[<a href="#s_ambientlevel">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0.3</span></p>
<div>
  <h4>Description</h4>
  <p>

Volume level of ambient sounds (produced by liquid and sky brushes).

</p>
</div>

  <h3 id="s_initsound">s_initsound&nbsp;<span>[<a href="#s_initsound">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>


</p>
</div>

  <h3 id="s_khz">s_khz&nbsp;<span>[<a href="#s_khz">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>44</span></p>
<div>
  <h4>Description</h4>
  <p>

Sound quality. Must be set from the commandline
Example:
ezquake-gl.exe +set s_khz 44

</p>
</div>

  <h3 id="s_loadas8bit">s_loadas8bit&nbsp;<span>[<a href="#s_loadas8bit">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Off.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>On (The sound samples will be loaded in 8-bit mode thus making them a little smaller. </td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>

This will give a little performance boost when playing the game at the cost of 
quality for the sound samples.)


</p>
</div>

  <h3 id="s_mixahead">s_mixahead&nbsp;<span>[<a href="#s_mixahead">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0.1</span></p>
<div>
  <h4>Description</h4>
  <p>
This variable defines the delay time for sounds. How low you can set your sound
mixahead depends on your FPS, when you set it too low, your sound will start 
crackling. Generally, with 72 FPS you should be able to use a delay of 0.06 
seconds, if you use the command-line switch "-primarysound", you may be able to
go even lower, but results may vary on this.

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="s_noextraupdate">s_noextraupdate&nbsp;<span>[<a href="#s_noextraupdate">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Makes Quake update its sound buffers more often to avoid choppy sound when your fps is really low (20 or worse)</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Don't use extra sound updates.  Gives a slight fps boost, but may lead to choppy sound on low-end machines</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="s_nosound">s_nosound&nbsp;<span>[<a href="#s_nosound">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Enable the playback of sounds.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Disable the playback of sounds.  Note that it effectively just resets sound volume to zero, but the sound engine still runs.  If you want disable sound in order to get more fps, use the -nosound command line option instead.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="s_precache">s_precache&nbsp;<span>[<a href="#s_precache">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable automatic sound caching.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable automatic sound caching.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="s_show">s_show&nbsp;<span>[<a href="#s_show">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable that the number of currently playing sound files is displayed.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable that the number of currently playing sound files is displayed.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="s_swapstereo">s_swapstereo&nbsp;<span>[<a href="#s_swapstereo">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Off</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Will swap left and right sound channels.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="volume">volume&nbsp;<span>[<a href="#volume">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0.7</span></p>
<div>
  <h4>Description</h4>
  <p>
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>No sound.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Maximum volume.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

