  <ul>
    <li><a href="#item-names">Item Names</a></li>
    <li><a href="#item-need-amounts">Item Need Amounts</a></li>
    <li><a href="#teamplay-communications">Teamplay Communications</a></li>
  </ul>
<h2 id="item-names">Item Names</h2>
  <h3 id="tp_name_armor">tp_name_armor&nbsp;<span>[<a href="#tp_name_armor">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>armor</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_armortype_ga">tp_name_armortype_ga&nbsp;<span>[<a href="#tp_name_armortype_ga">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>g</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_armortype_ra">tp_name_armortype_ra&nbsp;<span>[<a href="#tp_name_armortype_ra">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>r</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_armortype_ya">tp_name_armortype_ya&nbsp;<span>[<a href="#tp_name_armortype_ya">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>y</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_at">tp_name_at&nbsp;<span>[<a href="#tp_name_at">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>at</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_axe">tp_name_axe&nbsp;<span>[<a href="#tp_name_axe">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>axe</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_backpack">tp_name_backpack&nbsp;<span>[<a href="#tp_name_backpack">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>pack</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_cells">tp_name_cells&nbsp;<span>[<a href="#tp_name_cells">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>cells</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_disp">tp_name_disp&nbsp;<span>[<a href="#tp_name_disp">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>dispenser</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_enemy">tp_name_enemy&nbsp;<span>[<a href="#tp_name_enemy">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>enemy</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_eyes">tp_name_eyes&nbsp;<span>[<a href="#tp_name_eyes">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>eyes</span></p>
<div>
  <h4>Description</h4>
  <p>Sets the name for ring (invisibility) powerup for teamplay messages.</p>
  <h4>Value</h4>
    <p>String. common values are 'eyes' or 'ring'</p>
  </div>

  <h3 id="tp_name_flag">tp_name_flag&nbsp;<span>[<a href="#tp_name_flag">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>flag</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_ga">tp_name_ga&nbsp;<span>[<a href="#tp_name_ga">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>ga</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_gl">tp_name_gl&nbsp;<span>[<a href="#tp_name_gl">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>gl</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_health">tp_name_health&nbsp;<span>[<a href="#tp_name_health">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>health</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_lg">tp_name_lg&nbsp;<span>[<a href="#tp_name_lg">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>lg</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_mh">tp_name_mh&nbsp;<span>[<a href="#tp_name_mh">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>mega</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_nails">tp_name_nails&nbsp;<span>[<a href="#tp_name_nails">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>nails</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_ng">tp_name_ng&nbsp;<span>[<a href="#tp_name_ng">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>ng</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_none">tp_name_none&nbsp;<span>[<a href="#tp_name_none">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span></span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_nothing">tp_name_nothing&nbsp;<span>[<a href="#tp_name_nothing">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>nothing</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_pent">tp_name_pent&nbsp;<span>[<a href="#tp_name_pent">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>pent</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_pented">tp_name_pented&nbsp;<span>[<a href="#tp_name_pented">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>pented</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_quad">tp_name_quad&nbsp;<span>[<a href="#tp_name_quad">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>quad</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_quaded">tp_name_quaded&nbsp;<span>[<a href="#tp_name_quaded">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>quaded</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_ra">tp_name_ra&nbsp;<span>[<a href="#tp_name_ra">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>ra</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_ring">tp_name_ring&nbsp;<span>[<a href="#tp_name_ring">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>ring</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_rl">tp_name_rl&nbsp;<span>[<a href="#tp_name_rl">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>rl</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_rockets">tp_name_rockets&nbsp;<span>[<a href="#tp_name_rockets">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>rockets</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_rune_1">tp_name_rune_1&nbsp;<span>[<a href="#tp_name_rune_1">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>resistance rune</span></p>
<div>
  <h4>Description</h4>
  <p>


Sets name of the first rune (Resistance Rune) used for teamplay messages.

</p>
</div>

  <h3 id="tp_name_rune_2">tp_name_rune_2&nbsp;<span>[<a href="#tp_name_rune_2">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>strength rune</span></p>
<div>
  <h4>Description</h4>
  <p>


Sets name of the second rune (Strength Rune) used for teamplay messages.

</p>
</div>

  <h3 id="tp_name_rune_3">tp_name_rune_3&nbsp;<span>[<a href="#tp_name_rune_3">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>haste rune</span></p>
<div>
  <h4>Description</h4>
  <p>


Sets name of the third rune (Haste Rune) used for teamplay messages.

</p>
</div>

  <h3 id="tp_name_rune_4">tp_name_rune_4&nbsp;<span>[<a href="#tp_name_rune_4">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>regeneration rune</span></p>
<div>
  <h4>Description</h4>
  <p>


Sets name of the fourth rune (Regeneration Rune) used for teamplay messages.

</p>
</div>

  <h3 id="tp_name_sentry">tp_name_sentry&nbsp;<span>[<a href="#tp_name_sentry">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>sentry gun</span></p>
<div>
  <h4>Description</h4>
  <p>Sets the name for sentry tower in teamplay messages.</p>
  <h4>Value</h4>
    <p>String. common values are 'sentry' or 'sentry gun'.</p>
  </div>

  <h3 id="tp_name_separator">tp_name_separator&nbsp;<span>[<a href="#tp_name_separator">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>/</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_sg">tp_name_sg&nbsp;<span>[<a href="#tp_name_sg">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>sg</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_shells">tp_name_shells&nbsp;<span>[<a href="#tp_name_shells">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>shells</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_sng">tp_name_sng&nbsp;<span>[<a href="#tp_name_sng">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>sng</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_someplace">tp_name_someplace&nbsp;<span>[<a href="#tp_name_someplace">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>someplace</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_ssg">tp_name_ssg&nbsp;<span>[<a href="#tp_name_ssg">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>ssg</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_status_blue">tp_name_status_blue&nbsp;<span>[<a href="#tp_name_status_blue">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>$B</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_status_green">tp_name_status_green&nbsp;<span>[<a href="#tp_name_status_green">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>$G</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_status_red">tp_name_status_red&nbsp;<span>[<a href="#tp_name_status_red">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>$R</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_status_yellow">tp_name_status_yellow&nbsp;<span>[<a href="#tp_name_status_yellow">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>$Y</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_suit">tp_name_suit&nbsp;<span>[<a href="#tp_name_suit">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>suit</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_teammate">tp_name_teammate&nbsp;<span>[<a href="#tp_name_teammate">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span></span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_weapon">tp_name_weapon&nbsp;<span>[<a href="#tp_name_weapon">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>weapon</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

  <h3 id="tp_name_ya">tp_name_ya&nbsp;<span>[<a href="#tp_name_ya">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>ya</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes item</p>
</div>

<h2 id="item-need-amounts">Item Need Amounts</h2>
  <h3 id="tp_need_cells">tp_need_cells&nbsp;<span>[<a href="#tp_need_cells">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>20</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_ga">tp_need_ga&nbsp;<span>[<a href="#tp_need_ga">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>50</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_health">tp_need_health&nbsp;<span>[<a href="#tp_need_health">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>50</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_nails">tp_need_nails&nbsp;<span>[<a href="#tp_need_nails">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>40</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_ra">tp_need_ra&nbsp;<span>[<a href="#tp_need_ra">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>50</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_rl">tp_need_rl&nbsp;<span>[<a href="#tp_need_rl">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_rockets">tp_need_rockets&nbsp;<span>[<a href="#tp_need_rockets">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>5</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_shells">tp_need_shells&nbsp;<span>[<a href="#tp_need_shells">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>10</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_weapon">tp_need_weapon&nbsp;<span>[<a href="#tp_need_weapon">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>35687</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

  <h3 id="tp_need_ya">tp_need_ya&nbsp;<span>[<a href="#tp_need_ya">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>50</span></p>
<div>
  <h4>Description</h4>
  <p>
Customizes the %u macro</p>
</div>

<h2 id="teamplay-communications">Teamplay Communications</h2>
  <h3 id="tp_forcetriggers">tp_forceTriggers&nbsp;<span>[<a href="#tp_forcetriggers">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>0</span></p>
<div>
  <h4>Description</h4>
  <p>

Controls whether f_took, f_death etc are forced to execute even if the game isn't a team game.
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Off.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>On.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="tp_loadlocs">tp_loadlocs&nbsp;<span>[<a href="#tp_loadlocs">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>
Controls whether to load locs for teamplay reporting.
Note: The locs should be in your "/id1/locs/",
"/ezquake/locs" or "/qw/locs" folder.
</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Off.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>On.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>




</p>
</div>

  <h3 id="tp_msgtriggers">tp_msgtriggers&nbsp;<span>[<a href="#tp_msgtriggers">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>Switches on/off message triggers</p>
  <h4>Value</h4>
    <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>0 = False</td>
        <td>Message triggers are off</td>
      </tr>
      <tr>
        <td>1 = True</td>
        <td>Message triggers are on</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>For ruleset 'Smackdown' message triggers always are off.</p>
</div>

  <h3 id="tp_soundtrigger">tp_soundtrigger&nbsp;<span>[<a href="#tp_soundtrigger">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>~</span></p>
<div>
  <h4>Description</h4>
  <p>
SoundTrigger like proxys.
A SoundTrigger must be terminated by either a CR, LF or filter. The .wav extension is not required at the end. Trigger is a character before the sound file.
Example:
filter #a
say_team I'm at %l ~location.wav"
say_team ~location.wav$\me: I'm at %l #a"
say_team ~location$\me: I'm at %l #a"
say_team I'm at %l ~location #a"

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

  <h3 id="tp_triggers">tp_triggers&nbsp;<span>[<a href="#tp_triggers">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>1</span></p>
<div>
  <h4>Description</h4>
  <p>

</p>
  <h4>Value</h4>
  <table class="values">
    <thead>
      <tr>
        <td>value</td>
        <td>description</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
0</td>
        <td>Disable tp triggers.</td>
      </tr>
      <tr>
        <td>1</td>
        <td>Enable tp triggers.</td>
      </tr>
    </tbody>
  </table>
  <h4>Remarks</h4>
  <p>



</p>
</div>

  <h3 id="tp_weapon_order">tp_weapon_order&nbsp;<span>[<a href="#tp_weapon_order">#</a>]</span></h3>
  <p class="support">Support: <span class="windows-software supported">Windows: Software</span> <span class="windows-opengl supported">Windows: OpenGL</span> <span class="linux-x11 supported">Linux: X11</span> <span class="linux-glx supported">Linux: GLX</span> <span class="linux-svga supported">Linux: SVGA</span> </p>
  <p class="default">Default: <span>78654321</span></p>
<div>
  <h4>Description</h4>
  <p>
This allows you to define the order from best to worst weapon. The default value
is "78564321", which means that the Rocket Launcher is the best weapon (impulse 7)
then Lightning Gun (impulse 8), Super Nailgun (impulse 5), Grenade Launcher
(impulse 6), Nailgun (impulse 4), Super Shotgun (impulse 3), Shotgun (impulse 2),
Axe (impulse 1).

</p>
  <h4>Remarks</h4>
  <p>

</p>
</div>

