"../../make/wget.exe" -O libexpat.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libexpat.lib
"../../make/wget.exe" -O libjpeg.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libjpeg.lib
"../../make/wget.exe" -O libpcre.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libpcre.lib
"../../make/wget.exe" -O libpng.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libpng.lib
"../../make/wget.exe" -O libtcl.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libtcl.lib
"../../make/wget.exe" -O libz.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libz.lib
"../../make/wget.exe" -O mgllt.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/mgllt.lib
"../../make/wget.exe" -O minizip.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/minizip.lib
"../../make/wget.exe" -O dinput.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/dinput.lib
"../../make/wget.exe" -O dsound.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/dsound.lib
"../../make/wget.exe" -O dxguid.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/dxguid.lib
"../../make/wget.exe" -O libircclient-static.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/libircclient-static.lib
"../../make/wget.exe" -O glew32.lib http://ezquake.svn.sourceforge.net/viewvc/*checkout*/ezquake/trunk/libs/windows-x86/glew32.lib
