#!/bin/sh
wget -O 'libexpat.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libexpat.a'
wget -O 'libircclient.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libircclient.a'
wget -O 'libjpeg.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libjpeg.a'
wget -O 'libpcre.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libpcre.a'
wget -O 'libpng.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libpng.a'
wget -O 'libtcl.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libtcl.a'
wget -O 'libz.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libz.a'
wget -O 'minizip.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/minizip.a'
wget -O 'libcurl.a' 'http://github.com/ezQuake/ezquake-libs/raw/master/linux-x86/libcurl.a'