#!/bin/sh
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libexpat.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libircclient.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libjpeg.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libpcre.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libpng.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libtcl.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libz.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/minizip.a'
fetch -aRr 'http://github.com/ezQuake/ezquake-libs/raw/master/freebsd-x86/libcurl.a'
